package no.unit.nva.model.instancetypes.book;

import static no.unit.nva.utils.MigratePublicationChannelIdTestUtils.PUBLISHER_PATH_ELEMENT;
import static no.unit.nva.utils.MigratePublicationChannelIdTestUtils.SERIES_PATH_ELEMENT;
import static no.unit.nva.utils.MigratePublicationChannelIdTestUtils.constructPublicationChannelId;
import static no.unit.nva.utils.MigratePublicationChannelIdTestUtils.getNewIdentifierByOldIdentifier;
import static no.unit.nva.utils.MigratePublicationChannelIdTestUtils.randomOldPublisherIdentifier;
import static no.unit.nva.utils.MigratePublicationChannelIdTestUtils.randomOldSeriesIdentifier;
import static no.unit.nva.utils.MigratePublicationChannelIdTestUtils.randomYear;
import static nva.commons.core.attempt.Try.attempt;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.core.Is.is;
import static org.hamcrest.core.IsEqual.equalTo;
import java.net.URI;
import no.unit.nva.commons.json.JsonUtils;
import no.unit.nva.model.Publication;
import no.unit.nva.model.contexttypes.Book;
import no.unit.nva.model.contexttypes.Publisher;
import no.unit.nva.model.contexttypes.Series;
import no.unit.nva.model.contexttypes.utils.ChannelType;
import org.junit.jupiter.api.Test;

public class MigrateBookMonographPublicationChannelIdTest {

    @Test
    void shouldReplaceOldSeriesIdWithNewIdInBookMonograph() {
        var year = randomYear();
        var oldIdentifier = randomOldSeriesIdentifier();
        var newIdentifier = getNewIdentifierByOldIdentifier(oldIdentifier, ChannelType.SERIES);
        var oldId = constructPublicationChannelId(year, oldIdentifier, SERIES_PATH_ELEMENT);
        var expectedNewId = constructPublicationChannelId(year, newIdentifier, SERIES_PATH_ELEMENT);
        var json = generateFullBookMonographWithSeriesId(oldId);
        var actualBookMonograph = attempt(
            () -> JsonUtils.dtoObjectMapper.readValue(json, Publication.class)).orElseThrow();
        var actualBook = extractAndCastSeriesFromPublication(actualBookMonograph);
        var actualBookSeries = (Series) actualBook.getSeries();
        assertThat(actualBookSeries.getId(), is(equalTo(expectedNewId)));
    }

    @Test
    void shouldReplaceOldPublisherIdWithNewIdInBookMonograph() {
        var year = randomYear();
        var oldIdentifier = randomOldPublisherIdentifier();
        var newIdentifier = getNewIdentifierByOldIdentifier(oldIdentifier, ChannelType.PUBLISHER);
        var oldId = constructPublicationChannelId(year, oldIdentifier, PUBLISHER_PATH_ELEMENT);
        var expectedNewId = constructPublicationChannelId(year, newIdentifier, PUBLISHER_PATH_ELEMENT);
        var json = generateFullBookMonographWithPublisherId(oldId);
        var actualBookMonograph = attempt(
            () -> JsonUtils.dtoObjectMapper.readValue(json, Publication.class)).orElseThrow();
        var actualBook = extractAndCastSeriesFromPublication(actualBookMonograph);
        var actualPublisher = (Publisher) actualBook.getPublisher();
        assertThat(actualPublisher.getId(), is(equalTo(expectedNewId)));
    }

    private static Book extractAndCastSeriesFromPublication(Publication publication) {
        return (Book) publication.getEntityDescription().getReference().getPublicationContext();
    }

    private String generateFullBookMonographWithSeriesId(URI id) {
        return "{\n"
               + "  \"type\" : \"Publication\",\n"
               + "  \"identifier\" : \"c443030e-9d56-43d8-afd1-8c89105af555\",\n"
               + "  \"status\" : \"PUBLISHED\",\n"
               + "  \"resourceOwner\" : {\n"
               + "    \"owner\" : \"h1DeELLJIB\",\n"
               + "    \"ownerAffiliation\" : \"https://www.example.org/suntin\"\n"
               + "  },\n"
               + "  \"publisher\" : {\n"
               + "    \"type\" : \"Organization\",\n"
               + "    \"id\" : \"https://www.example.org/quiaest\",\n"
               + "    \"labels\" : {\n"
               + "      \"cs\" : \"PjcOaZOECQDGy\"\n"
               + "    }\n"
               + "  },\n"
               + "  \"createdDate\" : \"1972-04-25T12:00:38.421Z\",\n"
               + "  \"modifiedDate\" : \"2020-03-22T04:40:40.628Z\",\n"
               + "  \"publishedDate\" : \"1995-10-30T11:10:11.769Z\",\n"
               + "  \"indexedDate\" : \"1978-08-06T17:00:24.897Z\",\n"
               + "  \"handle\" : \"https://www.example.org/quotemporibus\",\n"
               + "  \"doi\" : \"https://doi.org/10.1234/at\",\n"
               + "  \"link\" : \"https://www.example.org/undemolestiae\",\n"
               + "  \"entityDescription\" : {\n"
               + "    \"type\" : \"EntityDescription\",\n"
               + "    \"mainTitle\" : \"yrsopI5kCQWvG\",\n"
               + "    \"alternativeTitles\" : {\n"
               + "      \"el\" : \"LrHbhkIdTNMka8lYR\"\n"
               + "    },\n"
               + "    \"language\" : \"http://lexvo.org/id/iso639-3/und\",\n"
               + "    \"publicationDate\" : {\n"
               + "      \"type\" : \"PublicationDate\",\n"
               + "      \"year\" : \"La85S7GlcY9moTzi2\",\n"
               + "      \"month\" : \"g36BRSYQzb\",\n"
               + "      \"day\" : \"k8IMQZpgZTHf1rwdx\"\n"
               + "    },\n"
               + "    \"contributors\" : [ {\n"
               + "      \"type\" : \"Contributor\",\n"
               + "      \"identity\" : {\n"
               + "        \"type\" : \"Identity\",\n"
               + "        \"id\" : \"https://www.example.com/az0LgBYWYyEjRqs6Hb3\",\n"
               + "        \"name\" : \"GyGyBr3IF0AgHE3\",\n"
               + "        \"nameType\" : \"Personal\",\n"
               + "        \"orcId\" : \"ut5BHj4TvPob\"\n"
               + "      },\n"
               + "      \"affiliations\" : [ {\n"
               + "        \"type\" : \"Organization\",\n"
               + "        \"id\" : \"https://www.example.com/AdRiOhitJFu62F6fD\",\n"
               + "        \"labels\" : {\n"
               + "          \"de\" : \"u5oNnZmOZDtI2\"\n"
               + "        }\n"
               + "      } ],\n"
               + "      \"role\" : {\n"
               + "        \"type\" : \"InteriorArchitect\"\n"
               + "      },\n"
               + "      \"sequence\" : 9,\n"
               + "      \"correspondingAuthor\" : false\n"
               + "    }, {\n"
               + "      \"type\" : \"Contributor\",\n"
               + "      \"identity\" : {\n"
               + "        \"type\" : \"Identity\",\n"
               + "        \"id\" : \"https://www.example.com/Lc54YoZBAY6BV8ZN\",\n"
               + "        \"name\" : \"5Hbin60QX36WTLuvCE\",\n"
               + "        \"nameType\" : \"Personal\",\n"
               + "        \"orcId\" : \"EeijHbpzBLA7iV\"\n"
               + "      },\n"
               + "      \"affiliations\" : [ {\n"
               + "        \"type\" : \"Organization\",\n"
               + "        \"id\" : \"https://www.example.com/kIbZjUbgCH9htct\",\n"
               + "        \"labels\" : {\n"
               + "          \"is\" : \"6YTjLkpqDrp15RCn\"\n"
               + "        }\n"
               + "      } ],\n"
               + "      \"role\" : {\n"
               + "        \"type\" : \"Researcher\"\n"
               + "      },\n"
               + "      \"sequence\" : 3,\n"
               + "      \"correspondingAuthor\" : false\n"
               + "    } ],\n"
               + "    \"alternativeAbstracts\" : {\n"
               + "      \"fi\" : \"ONGhtgmmFIWgY7z\"\n"
               + "    },\n"
               + "    \"npiSubjectHeading\" : \"fxDmmtlD0SkDvhN\",\n"
               + "    \"tags\" : [ \"pn2gE3KP5raO0GQuawF\" ],\n"
               + "    \"description\" : \"JU34tmP5OA6tQfSZI\",\n"
               + "    \"reference\" : {\n"
               + "      \"type\" : \"Reference\",\n"
               + "      \"publicationContext\" : {\n"
               + "        \"type\" : \"Book\",\n"
               + "        \"series\" : {\n"
               + "          \"type\" : \"Series\",\n"
               + "        \"id\" : \"" + id.toString() + "\"\n"
               + "        },\n"
               + "        \"seriesNumber\" : \"Va6iSLlmrR8o7\",\n"
               + "        \"publisher\" : {\n"
               + "          \"type\" : \"Publisher\",\n"
               + "          \"id\" : \"https://api.dev.nva.aws.unit.no/publication-channels/kv4kczj0C2pU8Um63MN\"\n"
               + "        },\n"
               + "        \"isbnList\" : [ \"9791871272344\" ]\n"
               + "      },\n"
               + "      \"doi\" : \"https://www.example.com/nHHEwOVgHdev2\",\n"
               + "      \"publicationInstance\" : {\n"
               + "        \"type\" : \"AcademicMonograph\",\n"
               + "        \"pages\" : {\n"
               + "          \"type\" : \"MonographPages\",\n"
               + "          \"introduction\" : {\n"
               + "            \"type\" : \"Range\",\n"
               + "            \"begin\" : \"SaDhkeYvtN03Xaxm11W\",\n"
               + "            \"end\" : \"vX2sZOXxDX9amofF3D\"\n"
               + "          },\n"
               + "          \"pages\" : \"NhTTTbGU91ci\",\n"
               + "          \"illustrated\" : true\n"
               + "        }\n"
               + "      }\n"
               + "    },\n"
               + "    \"metadataSource\" : \"https://www.example.com/YwRgc5IcSasGi7Tg99U\",\n"
               + "    \"abstract\" : \"oY2NpkdF9XZqsaW\"\n"
               + "  },\n"
               + "  \"projects\" : [ {\n"
               + "    \"type\" : \"ResearchProject\",\n"
               + "    \"id\" : \"https://www.example.org/ducimusconsequatur\",\n"
               + "    \"name\" : \"tCDsCnmuwwNjF\",\n"
               + "    \"approvals\" : [ {\n"
               + "      \"type\" : \"Approval\",\n"
               + "      \"approvalDate\" : \"1999-08-30T14:53:44.157Z\",\n"
               + "      \"approvedBy\" : \"REK\",\n"
               + "      \"approvalStatus\" : \"APPROVED\",\n"
               + "      \"applicationCode\" : \"BnUqhLSRtIN0S\"\n"
               + "    } ]\n"
               + "  } ],\n"
               + "  \"fundings\" : [ {\n"
               + "    \"type\" : \"UnconfirmedFunding\",\n"
               + "    \"source\" : \"https://www.example.org/estet\",\n"
               + "    \"identifier\" : \"WXKu4aWoH5\",\n"
               + "    \"labels\" : {\n"
               + "      \"se\" : \"9bWRjLCyBViLdVOR\"\n"
               + "    },\n"
               + "    \"fundingAmount\" : {\n"
               + "      \"currency\" : \"EUR\",\n"
               + "      \"amount\" : 771029579\n"
               + "    },\n"
               + "    \"activeFrom\" : \"1986-01-07T07:51:59.291Z\",\n"
               + "    \"activeTo\" : \"2014-01-19T04:38:55.906Z\"\n"
               + "  }, {\n"
               + "    \"type\" : \"ConfirmedFunding\",\n"
               + "    \"source\" : \"https://www.example.org/auteaque\",\n"
               + "    \"id\" : \"https://www.example.org/remcorrupti\",\n"
               + "    \"identifier\" : \"Dyn51RXJvc\",\n"
               + "    \"labels\" : {\n"
               + "      \"ru\" : \"cFf95cXQJMV\"\n"
               + "    },\n"
               + "    \"fundingAmount\" : {\n"
               + "      \"currency\" : \"EUR\",\n"
               + "      \"amount\" : 1553586329\n"
               + "    },\n"
               + "    \"activeFrom\" : \"2017-12-30T05:41:54.905Z\",\n"
               + "    \"activeTo\" : \"2021-04-09T08:09:17.674Z\"\n"
               + "  } ],\n"
               + "  \"additionalIdentifiers\" : [ {\n"
               + "    \"type\" : \"AdditionalIdentifier\",\n"
               + "    \"source\" : \"fakesource\",\n"
               + "    \"value\" : \"1234\"\n"
               + "  } ],\n"
               + "  \"subjects\" : [ \"https://www.example.org/atmodi\" ],\n"
               + "  \"associatedArtifacts\" : [ {\n"
               + "    \"type\" : \"PublishedFile\",\n"
               + "    \"identifier\" : \"84d142db-3e82-4183-934d-6c951d17b161\",\n"
               + "    \"name\" : \"NlXFHA85obdQ2\",\n"
               + "    \"mimeType\" : \"dxqew12u9ilGJFY8EVJ\",\n"
               + "    \"size\" : 604033003,\n"
               + "    \"license\" : {\n"
               + "      \"type\" : \"License\",\n"
               + "      \"identifier\" : \"cF0Z1p0Y4uw\",\n"
               + "      \"labels\" : {\n"
               + "        \"fr\" : \"RWpcxVPvqFL1bQmonhl\"\n"
               + "      },\n"
               + "      \"link\" : \"https://www.example.com/XbXLtF0CTeRr\"\n"
               + "    },\n"
               + "    \"administrativeAgreement\" : false,\n"
               + "    \"publisherAuthority\" : true,\n"
               + "    \"publishedDate\" : \"1980-03-16T04:22:14.459Z\",\n"
               + "    \"visibleForNonOwner\" : true\n"
               + "  }, {\n"
               + "    \"type\" : \"AssociatedLink\",\n"
               + "    \"id\" : \"https://www.example.com/4rTgBGn10E2y\",\n"
               + "    \"name\" : \"oHBCNGfgJOoCgu\",\n"
               + "    \"description\" : \"LbbaH3Uv1sFIPG5\"\n"
               + "  } ],\n"
               + "  \"rightsHolder\" : \"3608QQrhMQKSnojz4eU\",\n"
               + "  \"modelVersion\" : \"0.20.19\"\n"
               + "}";
    }

    private String generateFullBookMonographWithPublisherId(URI id) {
        return "{\n"
               + "  \"type\" : \"Publication\",\n"
               + "  \"identifier\" : \"c443030e-9d56-43d8-afd1-8c89105af555\",\n"
               + "  \"status\" : \"PUBLISHED\",\n"
               + "  \"resourceOwner\" : {\n"
               + "    \"owner\" : \"h1DeELLJIB\",\n"
               + "    \"ownerAffiliation\" : \"https://www.example.org/suntin\"\n"
               + "  },\n"
               + "  \"publisher\" : {\n"
               + "    \"type\" : \"Organization\",\n"
               + "    \"id\" : \"https://www.example.org/quiaest\",\n"
               + "    \"labels\" : {\n"
               + "      \"cs\" : \"PjcOaZOECQDGy\"\n"
               + "    }\n"
               + "  },\n"
               + "  \"createdDate\" : \"1972-04-25T12:00:38.421Z\",\n"
               + "  \"modifiedDate\" : \"2020-03-22T04:40:40.628Z\",\n"
               + "  \"publishedDate\" : \"1995-10-30T11:10:11.769Z\",\n"
               + "  \"indexedDate\" : \"1978-08-06T17:00:24.897Z\",\n"
               + "  \"handle\" : \"https://www.example.org/quotemporibus\",\n"
               + "  \"doi\" : \"https://doi.org/10.1234/at\",\n"
               + "  \"link\" : \"https://www.example.org/undemolestiae\",\n"
               + "  \"entityDescription\" : {\n"
               + "    \"type\" : \"EntityDescription\",\n"
               + "    \"mainTitle\" : \"yrsopI5kCQWvG\",\n"
               + "    \"alternativeTitles\" : {\n"
               + "      \"el\" : \"LrHbhkIdTNMka8lYR\"\n"
               + "    },\n"
               + "    \"language\" : \"http://lexvo.org/id/iso639-3/und\",\n"
               + "    \"publicationDate\" : {\n"
               + "      \"type\" : \"PublicationDate\",\n"
               + "      \"year\" : \"La85S7GlcY9moTzi2\",\n"
               + "      \"month\" : \"g36BRSYQzb\",\n"
               + "      \"day\" : \"k8IMQZpgZTHf1rwdx\"\n"
               + "    },\n"
               + "    \"contributors\" : [ {\n"
               + "      \"type\" : \"Contributor\",\n"
               + "      \"identity\" : {\n"
               + "        \"type\" : \"Identity\",\n"
               + "        \"id\" : \"https://www.example.com/az0LgBYWYyEjRqs6Hb3\",\n"
               + "        \"name\" : \"GyGyBr3IF0AgHE3\",\n"
               + "        \"nameType\" : \"Personal\",\n"
               + "        \"orcId\" : \"ut5BHj4TvPob\"\n"
               + "      },\n"
               + "      \"affiliations\" : [ {\n"
               + "        \"type\" : \"Organization\",\n"
               + "        \"id\" : \"https://www.example.com/AdRiOhitJFu62F6fD\",\n"
               + "        \"labels\" : {\n"
               + "          \"de\" : \"u5oNnZmOZDtI2\"\n"
               + "        }\n"
               + "      } ],\n"
               + "      \"role\" : {\n"
               + "        \"type\" : \"InteriorArchitect\"\n"
               + "      },\n"
               + "      \"sequence\" : 9,\n"
               + "      \"correspondingAuthor\" : false\n"
               + "    }, {\n"
               + "      \"type\" : \"Contributor\",\n"
               + "      \"identity\" : {\n"
               + "        \"type\" : \"Identity\",\n"
               + "        \"id\" : \"https://www.example.com/Lc54YoZBAY6BV8ZN\",\n"
               + "        \"name\" : \"5Hbin60QX36WTLuvCE\",\n"
               + "        \"nameType\" : \"Personal\",\n"
               + "        \"orcId\" : \"EeijHbpzBLA7iV\"\n"
               + "      },\n"
               + "      \"affiliations\" : [ {\n"
               + "        \"type\" : \"Organization\",\n"
               + "        \"id\" : \"https://www.example.com/kIbZjUbgCH9htct\",\n"
               + "        \"labels\" : {\n"
               + "          \"is\" : \"6YTjLkpqDrp15RCn\"\n"
               + "        }\n"
               + "      } ],\n"
               + "      \"role\" : {\n"
               + "        \"type\" : \"Researcher\"\n"
               + "      },\n"
               + "      \"sequence\" : 3,\n"
               + "      \"correspondingAuthor\" : false\n"
               + "    } ],\n"
               + "    \"alternativeAbstracts\" : {\n"
               + "      \"fi\" : \"ONGhtgmmFIWgY7z\"\n"
               + "    },\n"
               + "    \"npiSubjectHeading\" : \"fxDmmtlD0SkDvhN\",\n"
               + "    \"tags\" : [ \"pn2gE3KP5raO0GQuawF\" ],\n"
               + "    \"description\" : \"JU34tmP5OA6tQfSZI\",\n"
               + "    \"reference\" : {\n"
               + "      \"type\" : \"Reference\",\n"
               + "      \"publicationContext\" : {\n"
               + "        \"type\" : \"Book\",\n"
               + "        \"series\" : {\n"
               + "          \"type\" : \"Series\",\n"
               + "          \"id\" : \"https://api.dev.nva.aws.unit.no/publication-channels/sfHOJTYmBeAcWA1\"\n"
               + "        },\n"
               + "        \"seriesNumber\" : \"Va6iSLlmrR8o7\",\n"
               + "        \"publisher\" : {\n"
               + "          \"type\" : \"Publisher\",\n"
               + "        \"id\" : \"" + id.toString() + "\"\n"
               + "        },\n"
               + "        \"isbnList\" : [ \"9791871272344\" ]\n"
               + "      },\n"
               + "      \"doi\" : \"https://www.example.com/nHHEwOVgHdev2\",\n"
               + "      \"publicationInstance\" : {\n"
               + "        \"type\" : \"AcademicMonograph\",\n"
               + "        \"pages\" : {\n"
               + "          \"type\" : \"MonographPages\",\n"
               + "          \"introduction\" : {\n"
               + "            \"type\" : \"Range\",\n"
               + "            \"begin\" : \"SaDhkeYvtN03Xaxm11W\",\n"
               + "            \"end\" : \"vX2sZOXxDX9amofF3D\"\n"
               + "          },\n"
               + "          \"pages\" : \"NhTTTbGU91ci\",\n"
               + "          \"illustrated\" : true\n"
               + "        }\n"
               + "      }\n"
               + "    },\n"
               + "    \"metadataSource\" : \"https://www.example.com/YwRgc5IcSasGi7Tg99U\",\n"
               + "    \"abstract\" : \"oY2NpkdF9XZqsaW\"\n"
               + "  },\n"
               + "  \"projects\" : [ {\n"
               + "    \"type\" : \"ResearchProject\",\n"
               + "    \"id\" : \"https://www.example.org/ducimusconsequatur\",\n"
               + "    \"name\" : \"tCDsCnmuwwNjF\",\n"
               + "    \"approvals\" : [ {\n"
               + "      \"type\" : \"Approval\",\n"
               + "      \"approvalDate\" : \"1999-08-30T14:53:44.157Z\",\n"
               + "      \"approvedBy\" : \"REK\",\n"
               + "      \"approvalStatus\" : \"APPROVED\",\n"
               + "      \"applicationCode\" : \"BnUqhLSRtIN0S\"\n"
               + "    } ]\n"
               + "  } ],\n"
               + "  \"fundings\" : [ {\n"
               + "    \"type\" : \"UnconfirmedFunding\",\n"
               + "    \"source\" : \"https://www.example.org/estet\",\n"
               + "    \"identifier\" : \"WXKu4aWoH5\",\n"
               + "    \"labels\" : {\n"
               + "      \"se\" : \"9bWRjLCyBViLdVOR\"\n"
               + "    },\n"
               + "    \"fundingAmount\" : {\n"
               + "      \"currency\" : \"EUR\",\n"
               + "      \"amount\" : 771029579\n"
               + "    },\n"
               + "    \"activeFrom\" : \"1986-01-07T07:51:59.291Z\",\n"
               + "    \"activeTo\" : \"2014-01-19T04:38:55.906Z\"\n"
               + "  }, {\n"
               + "    \"type\" : \"ConfirmedFunding\",\n"
               + "    \"source\" : \"https://www.example.org/auteaque\",\n"
               + "    \"id\" : \"https://www.example.org/remcorrupti\",\n"
               + "    \"identifier\" : \"Dyn51RXJvc\",\n"
               + "    \"labels\" : {\n"
               + "      \"ru\" : \"cFf95cXQJMV\"\n"
               + "    },\n"
               + "    \"fundingAmount\" : {\n"
               + "      \"currency\" : \"EUR\",\n"
               + "      \"amount\" : 1553586329\n"
               + "    },\n"
               + "    \"activeFrom\" : \"2017-12-30T05:41:54.905Z\",\n"
               + "    \"activeTo\" : \"2021-04-09T08:09:17.674Z\"\n"
               + "  } ],\n"
               + "  \"additionalIdentifiers\" : [ {\n"
               + "    \"type\" : \"AdditionalIdentifier\",\n"
               + "    \"source\" : \"fakesource\",\n"
               + "    \"value\" : \"1234\"\n"
               + "  } ],\n"
               + "  \"subjects\" : [ \"https://www.example.org/atmodi\" ],\n"
               + "  \"associatedArtifacts\" : [ {\n"
               + "    \"type\" : \"PublishedFile\",\n"
               + "    \"identifier\" : \"84d142db-3e82-4183-934d-6c951d17b161\",\n"
               + "    \"name\" : \"NlXFHA85obdQ2\",\n"
               + "    \"mimeType\" : \"dxqew12u9ilGJFY8EVJ\",\n"
               + "    \"size\" : 604033003,\n"
               + "    \"license\" : {\n"
               + "      \"type\" : \"License\",\n"
               + "      \"identifier\" : \"cF0Z1p0Y4uw\",\n"
               + "      \"labels\" : {\n"
               + "        \"fr\" : \"RWpcxVPvqFL1bQmonhl\"\n"
               + "      },\n"
               + "      \"link\" : \"https://www.example.com/XbXLtF0CTeRr\"\n"
               + "    },\n"
               + "    \"administrativeAgreement\" : false,\n"
               + "    \"publisherAuthority\" : true,\n"
               + "    \"publishedDate\" : \"1980-03-16T04:22:14.459Z\",\n"
               + "    \"visibleForNonOwner\" : true\n"
               + "  }, {\n"
               + "    \"type\" : \"AssociatedLink\",\n"
               + "    \"id\" : \"https://www.example.com/4rTgBGn10E2y\",\n"
               + "    \"name\" : \"oHBCNGfgJOoCgu\",\n"
               + "    \"description\" : \"LbbaH3Uv1sFIPG5\"\n"
               + "  } ],\n"
               + "  \"rightsHolder\" : \"3608QQrhMQKSnojz4eU\",\n"
               + "  \"modelVersion\" : \"0.20.19\"\n"
               + "}";
    }
}
