package no.unit.nva;

import static org.junit.jupiter.api.Assertions.assertDoesNotThrow;
import java.util.stream.Stream;
import no.unit.nva.commons.json.JsonUtils;
import no.unit.nva.model.Publication;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Named;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.MethodSource;

@Deprecated
public class MigrateHandleToHandleListTest {

    public static Stream<Named<String>> publicationWithHandles() {
        return Stream.of(Named.of("Single handle", generatePublicationWithHandle()),
                                  Named.of("List of handles", generatePublicationWithListOfHandles()));
    }

    @DisplayName("Should accept handles")
    @ParameterizedTest()
    @MethodSource("publicationWithHandles")
    void shouldMigrateHandle(String publication) {
        assertDoesNotThrow(() -> JsonUtils.dtoObjectMapper.readValue(publication, Publication.class));
    }

    private static String generatePublicationWithHandle() {
        return "{\n"
               + "  \"type\" : \"Publication\",\n"
               + "  \"identifier\" : \"01897268ffda-2cbebd80-1faf-4ee0-b768-1089417f61ea\",\n"
               + "  \"status\" : \"PUBLISHED\",\n"
               + "  \"resourceOwner\" : {\n"
               + "    \"owner\" : \"hvlopen@203.0.0.0\",\n"
               + "    \"ownerAffiliation\" : \"https://api.sandbox.nva.aws.unit.no/cristin/organization/203.0.0.0\"\n"
               + "  },\n"
               + "  \"publisher\" : {\n"
               + "    \"type\" : \"Organization\",\n"
               + "    \"id\" : \"https://api.dev.nva.aws.unit.no/customer/fe945ea8-22d1-481c-b5be-4e0447d5656c\",\n"
               + "    \"labels\" : { }\n"
               + "  },\n"
               + "  \"createdDate\" : \"2022-03-21T14:54:39Z\",\n"
               + "  \"modifiedDate\" : \"2023-07-27T08:03:28.781096Z\",\n"
               + "  \"publishedDate\" : \"2022-03-21T14:54:39Z\",\n"
               + "  \"handle\" : \"https://hdl.handle.net/11250/3008547\",\n"
               + "  \"entityDescription\" : {\n"
               + "    \"type\" : \"EntityDescription\",\n"
               + "    \"mainTitle\" : \"Tracking of cardiometabolic risk in a Brazilian schoolchildren cohort: A "
               + "3-year longitudinal study\",\n"
               + "    \"alternativeTitles\" : { },\n"
               + "    \"language\" : \"http://lexvo.org/id/iso639-3/eng\",\n"
               + "    \"publicationDate\" : {\n"
               + "      \"type\" : \"PublicationDate\",\n"
               + "      \"year\" : \"2021\"\n"
               + "    },\n"
               + "    \"contributors\" : [ {\n"
               + "      \"type\" : \"Contributor\",\n"
               + "      \"identity\" : {\n"
               + "        \"type\" : \"Identity\",\n"
               + "        \"name\" : \"Cézane P. Reuter\"\n"
               + "      },\n"
               + "      \"affiliations\" : [ ],\n"
               + "      \"role\" : {\n"
               + "        \"type\" : \"Creator\"\n"
               + "      },\n"
               + "      \"correspondingAuthor\" : false\n"
               + "    }, {\n"
               + "      \"type\" : \"Contributor\",\n"
               + "      \"identity\" : {\n"
               + "        \"type\" : \"Identity\",\n"
               + "        \"name\" : \"Lars Bo Andersen\"\n"
               + "      },\n"
               + "      \"affiliations\" : [ ],\n"
               + "      \"role\" : {\n"
               + "        \"type\" : \"Creator\"\n"
               + "      },\n"
               + "      \"correspondingAuthor\" : false\n"
               + "    }, {\n"
               + "      \"type\" : \"Contributor\",\n"
               + "      \"identity\" : {\n"
               + "        \"type\" : \"Identity\",\n"
               + "        \"name\" : \"Letícia Welser\"\n"
               + "      },\n"
               + "      \"affiliations\" : [ ],\n"
               + "      \"role\" : {\n"
               + "        \"type\" : \"Creator\"\n"
               + "      },\n"
               + "      \"correspondingAuthor\" : false\n"
               + "    }, {\n"
               + "      \"type\" : \"Contributor\",\n"
               + "      \"identity\" : {\n"
               + "        \"type\" : \"Identity\",\n"
               + "        \"name\" : \"Hildegard H. Pohl\"\n"
               + "      },\n"
               + "      \"affiliations\" : [ ],\n"
               + "      \"role\" : {\n"
               + "        \"type\" : \"Creator\"\n"
               + "      },\n"
               + "      \"correspondingAuthor\" : false\n"
               + "    }, {\n"
               + "      \"type\" : \"Contributor\",\n"
               + "      \"identity\" : {\n"
               + "        \"type\" : \"Identity\",\n"
               + "        \"name\" : \"João F. Silveira\"\n"
               + "      },\n"
               + "      \"affiliations\" : [ ],\n"
               + "      \"role\" : {\n"
               + "        \"type\" : \"Creator\"\n"
               + "      },\n"
               + "      \"correspondingAuthor\" : false\n"
               + "    }, {\n"
               + "      \"type\" : \"Contributor\",\n"
               + "      \"identity\" : {\n"
               + "        \"type\" : \"Identity\",\n"
               + "        \"name\" : \"Rodrigo Antunes Lima\"\n"
               + "      },\n"
               + "      \"affiliations\" : [ ],\n"
               + "      \"role\" : {\n"
               + "        \"type\" : \"Creator\"\n"
               + "      },\n"
               + "      \"correspondingAuthor\" : false\n"
               + "    }, {\n"
               + "      \"type\" : \"Contributor\",\n"
               + "      \"identity\" : {\n"
               + "        \"type\" : \"Identity\",\n"
               + "        \"name\" : \"Karin Allor Pfeiffer\"\n"
               + "      },\n"
               + "      \"affiliations\" : [ ],\n"
               + "      \"role\" : {\n"
               + "        \"type\" : \"Creator\"\n"
               + "      },\n"
               + "      \"correspondingAuthor\" : false\n"
               + "    } ],\n"
               + "    \"alternativeAbstracts\" : { },\n"
               + "    \"tags\" : [ ],\n"
               + "    \"description\" : \"This is an author's accepted manuscript version of an article published by "
               + "Edizioni Minerva Medica in The Journal of Sports Medicine and Physical Fitness on 23 July 2021, "
               + "available from https://doi.org/10.23736/S0022-4707.20.11479-8\\n\",\n"
               + "    \"reference\" : {\n"
               + "      \"type\" : \"Reference\",\n"
               + "      \"publicationContext\" : {\n"
               + "        \"type\" : \"Journal\",\n"
               + "        \"id\" : \"https://api.dev.nva.aws.unit.no/publication-channels/journal/443787/2021\"\n"
               + "      },\n"
               + "      \"publicationInstance\" : {\n"
               + "        \"type\" : \"AcademicArticle\",\n"
               + "        \"pages\" : {\n"
               + "          \"type\" : \"Range\",\n"
               + "          \"begin\" : \"997\",\n"
               + "          \"end\" : \"1006\"\n"
               + "        },\n"
               + "        \"volume\" : \"61\",\n"
               + "        \"issue\" : \"7\"\n"
               + "      }\n"
               + "    },\n"
               + "    \"abstract\" : \"Background: Clustering of cardiometabolic risk factors is a sign of "
               + "detrimental health. Tracking is a term used to describe a variable longitudinal stability across "
               + "time. High tracking provides the chance to determine which cardiometabolic risk factors should be "
               + "the target of early treatment and prevention efforts. The present study aims to analyze the "
               + "tracking of cardiometabolic risk factors and clustered cardiometabolic risk score in children "
               + "across a 3-year time span, and to verify the odds of staying at risk (measured by the clustered "
               + "score) from baseline to follow-up. Methods: Longitudinal study that included 354 (155 boys) "
               + "children, aged 7-12 years at baseline. A clustered score was calculated by summing the systolic "
               + "blood pressure, waist circumference, triglycerides, glucose, and the TC/HDL-C ratio Z-scores "
               + "divided by five. A second clustered score was calculated including cardiorespiratory fitness (CRF)."
               + " Results: CRF and anthropometric parameters presented high tracking (r≥0.662), whereas the "
               + "cardiometabolic parameters exhibited low-to-moderate tracking (0.100≤r≤0.571). The clustered "
               + "scores' tracking was moderate (r≥0.508; r≥0.588 [CRF]). Participants in the higher risk groups at "
               + "baseline presented 3.81 (95% CI: 2.40; 6.05) and 4.64 (95% CI: 2.85; 7.56), including CRF, times "
               + "higher chance of remaining at risk three years later. Moreover, participants in the worst profile "
               + "regarding CRF or anthropometrics at baseline presented at least 4.00 times higher chance of being "
               + "at risk three years later. Conclusions: Participants with worst CRF and adiposity had an increased "
               + "risk of presenting higher clustered risk after three years.\\n\"\n"
               + "  },\n"
               + "  \"projects\" : [ ],\n"
               + "  \"fundings\" : [ ],\n"
               + "  \"subjects\" : [ ],\n"
               + "  \"associatedArtifacts\" : [ {\n"
               + "    \"type\" : \"PublishedFile\",\n"
               + "    \"identifier\" : \"baf5c2ba-af4c-4da8-9dd8-bb90416aa0ee\",\n"
               + "    \"name\" : \"Silveira.pdf\",\n"
               + "    \"mimeType\" : \"application/pdf\",\n"
               + "    \"size\" : 339921,\n"
               + "    \"license\" : \"https://rightsstatements.org/page/inc/1.0\",\n"
               + "    \"administrativeAgreement\" : false,\n"
               + "    \"publisherAuthority\" : false,\n"
               + "    \"publishedDate\" : \"2023-07-20T08:27:11.189561Z\",\n"
               + "    \"visibleForNonOwner\" : true\n"
               + "  } ],\n"
               + "  \"additionalIdentifiers\" : [ {\n"
               + "    \"type\" : \"AdditionalIdentifier\",\n"
               + "    \"sourceName\" : \"Cristin\",\n"
               + "    \"value\" : \"1924308\"\n"
               + "  } ],\n"
               + "  \"@context\" : {\n"
               + "    \"@vocab\" : \"https://nva.sikt.no/ontology/publication#\",\n"
               + "    \"xsd\" : \"http://www.w3.org/2001/XMLSchema#\",\n"
               + "    \"id\" : \"@id\",\n"
               + "    \"type\" : \"@type\",\n"
               + "    \"affiliations\" : {\n"
               + "      \"@id\" : \"affiliation\",\n"
               + "      \"@container\" : \"@set\"\n"
               + "    },\n"
               + "    \"activeFrom\" : {\n"
               + "      \"@type\" : \"xsd:dateTime\"\n"
               + "    },\n"
               + "    \"activeTo\" : {\n"
               + "      \"@type\" : \"xsd:dateTime\"\n"
               + "    },\n"
               + "    \"associatedArtifacts\" : {\n"
               + "      \"@id\" : \"associatedArtifact\",\n"
               + "      \"@container\" : \"@set\"\n"
               + "    },\n"
               + "    \"additionalIdentifiers\" : {\n"
               + "      \"@id\" : \"additionalIdentifier\",\n"
               + "      \"@container\" : \"@set\"\n"
               + "    },\n"
               + "    \"alternativeTitles\" : {\n"
               + "      \"@id\" : \"alternativeTitle\",\n"
               + "      \"@container\" : \"@language\"\n"
               + "    },\n"
               + "    \"approvals\" : {\n"
               + "      \"@id\" : \"approval\",\n"
               + "      \"@container\" : \"@set\"\n"
               + "    },\n"
               + "    \"approvalStatus\" : {\n"
               + "      \"@type\" : \"@vocab\",\n"
               + "      \"@context\" : {\n"
               + "        \"@vocab\" : \"https://nva.sikt.no/ontology/publication#\"\n"
               + "      }\n"
               + "    },\n"
               + "    \"approvedBy\" : {\n"
               + "      \"@type\" : \"@vocab\",\n"
               + "      \"@context\" : {\n"
               + "        \"@vocab\" : \"https://nva.sikt.no/ontology/approvals-body#\"\n"
               + "      }\n"
               + "    },\n"
               + "    \"architectureOutput\" : {\n"
               + "      \"@id\" : \"architectureOutput\",\n"
               + "      \"@container\" : \"@set\"\n"
               + "    },\n"
               + "    \"compliesWith\" : {\n"
               + "      \"@id\" : \"compliesWith\",\n"
               + "      \"@container\" : \"@set\"\n"
               + "    },\n"
               + "    \"concertProgramme\" : {\n"
               + "      \"@id\" : \"concertProgramme\",\n"
               + "      \"@container\" : \"@set\"\n"
               + "    },\n"
               + "    \"contributors\" : {\n"
               + "      \"@id\" : \"contributor\",\n"
               + "      \"@container\" : \"@set\"\n"
               + "    },\n"
               + "    \"createdDate\" : {\n"
               + "      \"@type\" : \"xsd:dateTime\"\n"
               + "    },\n"
               + "    \"date\" : {\n"
               + "      \"@type\" : \"xsd:dateTime\"\n"
               + "    },\n"
               + "    \"doi\" : {\n"
               + "      \"@type\" : \"@id\"\n"
               + "    },\n"
               + "    \"embargoDate\" : {\n"
               + "      \"@type\" : \"xsd:dateTime\"\n"
               + "    },\n"
               + "    \"from\" : {\n"
               + "      \"@type\" : \"xsd:dateTime\"\n"
               + "    },\n"
               + "    \"handle\" : {\n"
               + "      \"@type\" : \"@id\"\n"
               + "    },\n"
               + "    \"indexedDate\" : {\n"
               + "      \"@type\" : \"xsd:dateTime\"\n"
               + "    },\n"
               + "    \"isbnList\" : {\n"
               + "      \"@id\" : \"isbn\",\n"
               + "      \"@container\" : \"@set\"\n"
               + "    },\n"
               + "    \"labels\" : {\n"
               + "      \"@id\" : \"label\",\n"
               + "      \"@container\" : \"@language\"\n"
               + "    },\n"
               + "    \"language\" : {\n"
               + "      \"@type\" : \"@id\"\n"
               + "    },\n"
               + "    \"link\" : {\n"
               + "      \"@type\" : \"@id\"\n"
               + "    },\n"
               + "    \"manifestations\" : {\n"
               + "      \"@id\" : \"manifestation\",\n"
               + "      \"@container\" : \"@set\"\n"
               + "    },\n"
               + "    \"metadataSource\" : {\n"
               + "      \"@type\" : \"@id\"\n"
               + "    },\n"
               + "    \"modifiedDate\" : {\n"
               + "      \"@type\" : \"xsd:dateTime\"\n"
               + "    },\n"
               + "    \"musicalWorks\" : {\n"
               + "      \"@id\" : \"musicalWork\",\n"
               + "      \"@container\" : \"@set\"\n"
               + "    },\n"
               + "    \"ownerAffiliation\" : {\n"
               + "      \"@type\" : \"@id\"\n"
               + "    },\n"
               + "    \"outputs\" : {\n"
               + "      \"@id\" : \"output\",\n"
               + "      \"@container\" : \"@set\"\n"
               + "    },\n"
               + "    \"publishedDate\" : {\n"
               + "      \"@type\" : \"xsd:dateTime\"\n"
               + "    },\n"
               + "    \"nameType\" : {\n"
               + "      \"@type\" : \"@vocab\",\n"
               + "      \"@context\" : {\n"
               + "        \"@vocab\" : \"https://nva.sikt.no/ontology/publication#\"\n"
               + "      }\n"
               + "    },\n"
               + "    \"projects\" : {\n"
               + "      \"@id\" : \"project\",\n"
               + "      \"@container\" : \"@set\"\n"
               + "    },\n"
               + "    \"fundings\" : {\n"
               + "      \"@id\" : \"funding\",\n"
               + "      \"@container\" : \"@set\"\n"
               + "    },\n"
               + "    \"related\" : {\n"
               + "      \"@id\" : \"related\",\n"
               + "      \"@container\" : \"@set\"\n"
               + "    },\n"
               + "    \"referencedBy\" : {\n"
               + "      \"@id\" : \"referencedBy\",\n"
               + "      \"@container\" : \"@set\"\n"
               + "    },\n"
               + "    \"role\" : {\n"
               + "      \"@type\" : \"@vocab\",\n"
               + "      \"@context\" : {\n"
               + "        \"@vocab\" : \"https://nva.sikt.no/ontology/publication#\"\n"
               + "      }\n"
               + "    },\n"
               + "    \"source\" : {\n"
               + "      \"@type\" : \"@id\"\n"
               + "    },\n"
               + "    \"status\" : {\n"
               + "      \"@type\" : \"@vocab\",\n"
               + "      \"@context\" : {\n"
               + "        \"@vocab\" : \"https://nva.sikt.no/ontology/publication#\"\n"
               + "      }\n"
               + "    },\n"
               + "    \"subjects\" : {\n"
               + "      \"@id\" : \"subject\",\n"
               + "      \"@type\" : \"@id\",\n"
               + "      \"@container\" : \"@set\"\n"
               + "    },\n"
               + "    \"tags\" : {\n"
               + "      \"@id\" : \"tag\",\n"
               + "      \"@container\" : \"@set\"\n"
               + "    },\n"
               + "    \"to\" : {\n"
               + "      \"@type\" : \"xsd:dateTime\"\n"
               + "    },\n"
               + "    \"trackList\" : {\n"
               + "      \"@id\" : \"trackList\",\n"
               + "      \"@container\" : \"@set\"\n"
               + "    },\n"
               + "    \"venues\" : {\n"
               + "      \"@id\" : \"venue\",\n"
               + "      \"@container\" : \"@set\"\n"
               + "    }\n"
               + "  },\n"
               + "  \"id\" : \"https://api.dev.nva.aws.unit"
               + ".no/publication/01897268ffda-2cbebd80-1faf-4ee0-b768-1089417f61ea\"\n"
               + "}";
    }

    private static String generatePublicationWithListOfHandles() {
        return "{\n"
               + "  \"type\" : \"Publication\",\n"
               + "  \"identifier\" : \"01897268ffda-2cbebd80-1faf-4ee0-b768-1089417f61ea\",\n"
               + "  \"status\" : \"PUBLISHED\",\n"
               + "  \"resourceOwner\" : {\n"
               + "    \"owner\" : \"hvlopen@203.0.0.0\",\n"
               + "    \"ownerAffiliation\" : \"https://api.sandbox.nva.aws.unit.no/cristin/organization/203.0.0.0\"\n"
               + "  },\n"
               + "  \"publisher\" : {\n"
               + "    \"type\" : \"Organization\",\n"
               + "    \"id\" : \"https://api.dev.nva.aws.unit.no/customer/fe945ea8-22d1-481c-b5be-4e0447d5656c\",\n"
               + "    \"labels\" : { }\n"
               + "  },\n"
               + "  \"createdDate\" : \"2022-03-21T14:54:39Z\",\n"
               + "  \"modifiedDate\" : \"2023-07-27T08:03:28.781096Z\",\n"
               + "  \"publishedDate\" : \"2022-03-21T14:54:39Z\",\n"
               + "  \"handles\" : [\"https://hdl.handle.net/11250/3008547\", \"https://hdl.handle.net/11250/12345\"],\n"
               + "  \"entityDescription\" : {\n"
               + "    \"type\" : \"EntityDescription\",\n"
               + "    \"mainTitle\" : \"Tracking of cardiometabolic risk in a Brazilian schoolchildren cohort: A "
               + "3-year longitudinal study\",\n"
               + "    \"alternativeTitles\" : { },\n"
               + "    \"language\" : \"http://lexvo.org/id/iso639-3/eng\",\n"
               + "    \"publicationDate\" : {\n"
               + "      \"type\" : \"PublicationDate\",\n"
               + "      \"year\" : \"2021\"\n"
               + "    },\n"
               + "    \"contributors\" : [ {\n"
               + "      \"type\" : \"Contributor\",\n"
               + "      \"identity\" : {\n"
               + "        \"type\" : \"Identity\",\n"
               + "        \"name\" : \"Cézane P. Reuter\"\n"
               + "      },\n"
               + "      \"affiliations\" : [ ],\n"
               + "      \"role\" : {\n"
               + "        \"type\" : \"Creator\"\n"
               + "      },\n"
               + "      \"correspondingAuthor\" : false\n"
               + "    }, {\n"
               + "      \"type\" : \"Contributor\",\n"
               + "      \"identity\" : {\n"
               + "        \"type\" : \"Identity\",\n"
               + "        \"name\" : \"Lars Bo Andersen\"\n"
               + "      },\n"
               + "      \"affiliations\" : [ ],\n"
               + "      \"role\" : {\n"
               + "        \"type\" : \"Creator\"\n"
               + "      },\n"
               + "      \"correspondingAuthor\" : false\n"
               + "    }, {\n"
               + "      \"type\" : \"Contributor\",\n"
               + "      \"identity\" : {\n"
               + "        \"type\" : \"Identity\",\n"
               + "        \"name\" : \"Letícia Welser\"\n"
               + "      },\n"
               + "      \"affiliations\" : [ ],\n"
               + "      \"role\" : {\n"
               + "        \"type\" : \"Creator\"\n"
               + "      },\n"
               + "      \"correspondingAuthor\" : false\n"
               + "    }, {\n"
               + "      \"type\" : \"Contributor\",\n"
               + "      \"identity\" : {\n"
               + "        \"type\" : \"Identity\",\n"
               + "        \"name\" : \"Hildegard H. Pohl\"\n"
               + "      },\n"
               + "      \"affiliations\" : [ ],\n"
               + "      \"role\" : {\n"
               + "        \"type\" : \"Creator\"\n"
               + "      },\n"
               + "      \"correspondingAuthor\" : false\n"
               + "    }, {\n"
               + "      \"type\" : \"Contributor\",\n"
               + "      \"identity\" : {\n"
               + "        \"type\" : \"Identity\",\n"
               + "        \"name\" : \"João F. Silveira\"\n"
               + "      },\n"
               + "      \"affiliations\" : [ ],\n"
               + "      \"role\" : {\n"
               + "        \"type\" : \"Creator\"\n"
               + "      },\n"
               + "      \"correspondingAuthor\" : false\n"
               + "    }, {\n"
               + "      \"type\" : \"Contributor\",\n"
               + "      \"identity\" : {\n"
               + "        \"type\" : \"Identity\",\n"
               + "        \"name\" : \"Rodrigo Antunes Lima\"\n"
               + "      },\n"
               + "      \"affiliations\" : [ ],\n"
               + "      \"role\" : {\n"
               + "        \"type\" : \"Creator\"\n"
               + "      },\n"
               + "      \"correspondingAuthor\" : false\n"
               + "    }, {\n"
               + "      \"type\" : \"Contributor\",\n"
               + "      \"identity\" : {\n"
               + "        \"type\" : \"Identity\",\n"
               + "        \"name\" : \"Karin Allor Pfeiffer\"\n"
               + "      },\n"
               + "      \"affiliations\" : [ ],\n"
               + "      \"role\" : {\n"
               + "        \"type\" : \"Creator\"\n"
               + "      },\n"
               + "      \"correspondingAuthor\" : false\n"
               + "    } ],\n"
               + "    \"alternativeAbstracts\" : { },\n"
               + "    \"tags\" : [ ],\n"
               + "    \"description\" : \"This is an author's accepted manuscript version of an article published by "
               + "Edizioni Minerva Medica in The Journal of Sports Medicine and Physical Fitness on 23 July 2021, "
               + "available from https://doi.org/10.23736/S0022-4707.20.11479-8\\n\",\n"
               + "    \"reference\" : {\n"
               + "      \"type\" : \"Reference\",\n"
               + "      \"publicationContext\" : {\n"
               + "        \"type\" : \"Journal\",\n"
               + "        \"id\" : \"https://api.dev.nva.aws.unit.no/publication-channels/journal/443787/2021\"\n"
               + "      },\n"
               + "      \"publicationInstance\" : {\n"
               + "        \"type\" : \"AcademicArticle\",\n"
               + "        \"pages\" : {\n"
               + "          \"type\" : \"Range\",\n"
               + "          \"begin\" : \"997\",\n"
               + "          \"end\" : \"1006\"\n"
               + "        },\n"
               + "        \"volume\" : \"61\",\n"
               + "        \"issue\" : \"7\"\n"
               + "      }\n"
               + "    },\n"
               + "    \"abstract\" : \"Background: Clustering of cardiometabolic risk factors is a sign of "
               + "detrimental health. Tracking is a term used to describe a variable longitudinal stability across "
               + "time. High tracking provides the chance to determine which cardiometabolic risk factors should be "
               + "the target of early treatment and prevention efforts. The present study aims to analyze the "
               + "tracking of cardiometabolic risk factors and clustered cardiometabolic risk score in children "
               + "across a 3-year time span, and to verify the odds of staying at risk (measured by the clustered "
               + "score) from baseline to follow-up. Methods: Longitudinal study that included 354 (155 boys) "
               + "children, aged 7-12 years at baseline. A clustered score was calculated by summing the systolic "
               + "blood pressure, waist circumference, triglycerides, glucose, and the TC/HDL-C ratio Z-scores "
               + "divided by five. A second clustered score was calculated including cardiorespiratory fitness (CRF)."
               + " Results: CRF and anthropometric parameters presented high tracking (r≥0.662), whereas the "
               + "cardiometabolic parameters exhibited low-to-moderate tracking (0.100≤r≤0.571). The clustered "
               + "scores' tracking was moderate (r≥0.508; r≥0.588 [CRF]). Participants in the higher risk groups at "
               + "baseline presented 3.81 (95% CI: 2.40; 6.05) and 4.64 (95% CI: 2.85; 7.56), including CRF, times "
               + "higher chance of remaining at risk three years later. Moreover, participants in the worst profile "
               + "regarding CRF or anthropometrics at baseline presented at least 4.00 times higher chance of being "
               + "at risk three years later. Conclusions: Participants with worst CRF and adiposity had an increased "
               + "risk of presenting higher clustered risk after three years.\\n\"\n"
               + "  },\n"
               + "  \"projects\" : [ ],\n"
               + "  \"fundings\" : [ ],\n"
               + "  \"subjects\" : [ ],\n"
               + "  \"associatedArtifacts\" : [ {\n"
               + "    \"type\" : \"PublishedFile\",\n"
               + "    \"identifier\" : \"baf5c2ba-af4c-4da8-9dd8-bb90416aa0ee\",\n"
               + "    \"name\" : \"Silveira.pdf\",\n"
               + "    \"mimeType\" : \"application/pdf\",\n"
               + "    \"size\" : 339921,\n"
               + "    \"license\" : \"https://rightsstatements.org/page/inc/1.0\",\n"
               + "    \"administrativeAgreement\" : false,\n"
               + "    \"publisherAuthority\" : false,\n"
               + "    \"publishedDate\" : \"2023-07-20T08:27:11.189561Z\",\n"
               + "    \"visibleForNonOwner\" : true\n"
               + "  } ],\n"
               + "  \"additionalIdentifiers\" : [ {\n"
               + "    \"type\" : \"AdditionalIdentifier\",\n"
               + "    \"sourceName\" : \"Cristin\",\n"
               + "    \"value\" : \"1924308\"\n"
               + "  } ],\n"
               + "  \"@context\" : {\n"
               + "    \"@vocab\" : \"https://nva.sikt.no/ontology/publication#\",\n"
               + "    \"xsd\" : \"http://www.w3.org/2001/XMLSchema#\",\n"
               + "    \"id\" : \"@id\",\n"
               + "    \"type\" : \"@type\",\n"
               + "    \"affiliations\" : {\n"
               + "      \"@id\" : \"affiliation\",\n"
               + "      \"@container\" : \"@set\"\n"
               + "    },\n"
               + "    \"activeFrom\" : {\n"
               + "      \"@type\" : \"xsd:dateTime\"\n"
               + "    },\n"
               + "    \"activeTo\" : {\n"
               + "      \"@type\" : \"xsd:dateTime\"\n"
               + "    },\n"
               + "    \"associatedArtifacts\" : {\n"
               + "      \"@id\" : \"associatedArtifact\",\n"
               + "      \"@container\" : \"@set\"\n"
               + "    },\n"
               + "    \"additionalIdentifiers\" : {\n"
               + "      \"@id\" : \"additionalIdentifier\",\n"
               + "      \"@container\" : \"@set\"\n"
               + "    },\n"
               + "    \"alternativeTitles\" : {\n"
               + "      \"@id\" : \"alternativeTitle\",\n"
               + "      \"@container\" : \"@language\"\n"
               + "    },\n"
               + "    \"approvals\" : {\n"
               + "      \"@id\" : \"approval\",\n"
               + "      \"@container\" : \"@set\"\n"
               + "    },\n"
               + "    \"approvalStatus\" : {\n"
               + "      \"@type\" : \"@vocab\",\n"
               + "      \"@context\" : {\n"
               + "        \"@vocab\" : \"https://nva.sikt.no/ontology/publication#\"\n"
               + "      }\n"
               + "    },\n"
               + "    \"approvedBy\" : {\n"
               + "      \"@type\" : \"@vocab\",\n"
               + "      \"@context\" : {\n"
               + "        \"@vocab\" : \"https://nva.sikt.no/ontology/approvals-body#\"\n"
               + "      }\n"
               + "    },\n"
               + "    \"architectureOutput\" : {\n"
               + "      \"@id\" : \"architectureOutput\",\n"
               + "      \"@container\" : \"@set\"\n"
               + "    },\n"
               + "    \"compliesWith\" : {\n"
               + "      \"@id\" : \"compliesWith\",\n"
               + "      \"@container\" : \"@set\"\n"
               + "    },\n"
               + "    \"concertProgramme\" : {\n"
               + "      \"@id\" : \"concertProgramme\",\n"
               + "      \"@container\" : \"@set\"\n"
               + "    },\n"
               + "    \"contributors\" : {\n"
               + "      \"@id\" : \"contributor\",\n"
               + "      \"@container\" : \"@set\"\n"
               + "    },\n"
               + "    \"createdDate\" : {\n"
               + "      \"@type\" : \"xsd:dateTime\"\n"
               + "    },\n"
               + "    \"date\" : {\n"
               + "      \"@type\" : \"xsd:dateTime\"\n"
               + "    },\n"
               + "    \"doi\" : {\n"
               + "      \"@type\" : \"@id\"\n"
               + "    },\n"
               + "    \"embargoDate\" : {\n"
               + "      \"@type\" : \"xsd:dateTime\"\n"
               + "    },\n"
               + "    \"from\" : {\n"
               + "      \"@type\" : \"xsd:dateTime\"\n"
               + "    },\n"
               + "    \"handle\" : {\n"
               + "      \"@type\" : \"@id\"\n"
               + "    },\n"
               + "    \"indexedDate\" : {\n"
               + "      \"@type\" : \"xsd:dateTime\"\n"
               + "    },\n"
               + "    \"isbnList\" : {\n"
               + "      \"@id\" : \"isbn\",\n"
               + "      \"@container\" : \"@set\"\n"
               + "    },\n"
               + "    \"labels\" : {\n"
               + "      \"@id\" : \"label\",\n"
               + "      \"@container\" : \"@language\"\n"
               + "    },\n"
               + "    \"language\" : {\n"
               + "      \"@type\" : \"@id\"\n"
               + "    },\n"
               + "    \"link\" : {\n"
               + "      \"@type\" : \"@id\"\n"
               + "    },\n"
               + "    \"manifestations\" : {\n"
               + "      \"@id\" : \"manifestation\",\n"
               + "      \"@container\" : \"@set\"\n"
               + "    },\n"
               + "    \"metadataSource\" : {\n"
               + "      \"@type\" : \"@id\"\n"
               + "    },\n"
               + "    \"modifiedDate\" : {\n"
               + "      \"@type\" : \"xsd:dateTime\"\n"
               + "    },\n"
               + "    \"musicalWorks\" : {\n"
               + "      \"@id\" : \"musicalWork\",\n"
               + "      \"@container\" : \"@set\"\n"
               + "    },\n"
               + "    \"ownerAffiliation\" : {\n"
               + "      \"@type\" : \"@id\"\n"
               + "    },\n"
               + "    \"outputs\" : {\n"
               + "      \"@id\" : \"output\",\n"
               + "      \"@container\" : \"@set\"\n"
               + "    },\n"
               + "    \"publishedDate\" : {\n"
               + "      \"@type\" : \"xsd:dateTime\"\n"
               + "    },\n"
               + "    \"nameType\" : {\n"
               + "      \"@type\" : \"@vocab\",\n"
               + "      \"@context\" : {\n"
               + "        \"@vocab\" : \"https://nva.sikt.no/ontology/publication#\"\n"
               + "      }\n"
               + "    },\n"
               + "    \"projects\" : {\n"
               + "      \"@id\" : \"project\",\n"
               + "      \"@container\" : \"@set\"\n"
               + "    },\n"
               + "    \"fundings\" : {\n"
               + "      \"@id\" : \"funding\",\n"
               + "      \"@container\" : \"@set\"\n"
               + "    },\n"
               + "    \"related\" : {\n"
               + "      \"@id\" : \"related\",\n"
               + "      \"@container\" : \"@set\"\n"
               + "    },\n"
               + "    \"referencedBy\" : {\n"
               + "      \"@id\" : \"referencedBy\",\n"
               + "      \"@container\" : \"@set\"\n"
               + "    },\n"
               + "    \"role\" : {\n"
               + "      \"@type\" : \"@vocab\",\n"
               + "      \"@context\" : {\n"
               + "        \"@vocab\" : \"https://nva.sikt.no/ontology/publication#\"\n"
               + "      }\n"
               + "    },\n"
               + "    \"source\" : {\n"
               + "      \"@type\" : \"@id\"\n"
               + "    },\n"
               + "    \"status\" : {\n"
               + "      \"@type\" : \"@vocab\",\n"
               + "      \"@context\" : {\n"
               + "        \"@vocab\" : \"https://nva.sikt.no/ontology/publication#\"\n"
               + "      }\n"
               + "    },\n"
               + "    \"subjects\" : {\n"
               + "      \"@id\" : \"subject\",\n"
               + "      \"@type\" : \"@id\",\n"
               + "      \"@container\" : \"@set\"\n"
               + "    },\n"
               + "    \"tags\" : {\n"
               + "      \"@id\" : \"tag\",\n"
               + "      \"@container\" : \"@set\"\n"
               + "    },\n"
               + "    \"to\" : {\n"
               + "      \"@type\" : \"xsd:dateTime\"\n"
               + "    },\n"
               + "    \"trackList\" : {\n"
               + "      \"@id\" : \"trackList\",\n"
               + "      \"@container\" : \"@set\"\n"
               + "    },\n"
               + "    \"venues\" : {\n"
               + "      \"@id\" : \"venue\",\n"
               + "      \"@container\" : \"@set\"\n"
               + "    }\n"
               + "  },\n"
               + "  \"id\" : \"https://api.dev.nva.aws.unit"
               + ".no/publication/01897268ffda-2cbebd80-1faf-4ee0-b768-1089417f61ea\"\n"
               + "}";
    }
}


